### ISSUE TITLE
Error bij openen subgait file

### ISSUE THREAD

**Issue by Roelemans** [project-march/gait-generation#63]
Ik maakte een mooie subgait, en toen exporte ik die. Nu probeer ik hem weer te importen en dan krijg ik de volgende error:

[INFO] [1566394537.966472]: Setting gait directory to /home/roel/march_ws/src/gait-files/march_gait_files/airgait
[ERROR] [1566394537.968192]: sequence entries are not allowed here
  in "/home/roel/march_ws/src/gait-files/march_gait_files/airgait/Rightstep/Rightstep/Rightstep.subgait", line 9, column 18
[WARN] [1566394537.968534]: Could not load gait /home/roel/march_ws/src/gait-files/march_gait_files/airgait/Rightstep/Rightstep/Rightstep.subgait

File:

```
name: ''
version: ''
description: "Just a simple sidestep"
setpoints: 
  - 
    time_from_start: 
      secs: 0
      nsecs: 200000000
    joint_names: - left_hip_aa
- left_hip_fe
- left_knee
- left_ankle
- right_hip_aa
- right_hip_fe
- right_knee
- right_ankle
  - 
    time_from_start: 
      secs: 0
      nsecs: 983000000
    joint_names: - left_hip_fe
  - 
    time_from_start: 
      secs: 1
      nsecs:   2399999
    joint_names: - left_ankle
  - 
    time_from_start: 
      secs: 1
      nsecs:  79700000
    joint_names: - left_knee
  - 
    time_from_start: 
      secs: 1
      nsecs: 953200000
    joint_names: - right_knee
  - 
    time_from_start: 
      secs: 2
      nsecs:  30800000
    joint_names: - right_hip_fe
  - 
    time_from_start: 
      secs: 2
      nsecs: 975000000
    joint_names: - left_hip_aa
  - 
    time_from_start: 
      secs: 2
      nsecs: 992200000
    joint_names: - right_hip_fe
  - 
    time_from_start: 
      secs: 2
      nsecs: 994300000
    joint_names: - left_ankle
  - 
    time_from_start: 
      secs: 3
      nsecs:  13700000
    joint_names: - left_hip_fe
- left_knee
  - 
    time_from_start: 
      secs: 3
      nsecs:  50399999
    joint_names: - right_hip_aa
  - 
    time_from_start: 
      secs: 3
      nsecs:  59800000
    joint_names: - right_knee
  - 
    time_from_start: 
      secs: 4
      nsecs:         0
    joint_names: - left_hip_fe
- left_knee
  - 
    time_from_start: 
      secs: 4
      nsecs:  19300000
    joint_names: - left_ankle
  - 
    time_from_start: 
      secs: 4
      nsecs: 959600000
    joint_names: - right_hip_aa
  - 
    time_from_start: 
      secs: 4
      nsecs: 987400000
    joint_names: - right_knee
  - 
    time_from_start: 
      secs: 5
      nsecs:  15699999
    joint_names: - left_hip_aa
  - 
    time_from_start: 
      secs: 5
      nsecs:  17699999
    joint_names: - right_hip_fe
  - 
    time_from_start: 
      secs: 8
      nsecs:         0
    joint_names: - left_hip_aa
- left_hip_fe
- left_knee
- left_ankle
- right_hip_aa
- right_hip_fe
- right_knee
- right_ankle
trajectory: 
  header: 
    seq: 0
    stamp: 
      secs: 0
      nsecs:         0
    frame_id: ''
  joint_names: - left_hip_aa
- left_hip_fe
- left_knee
- left_ankle
- right_hip_aa
- right_hip_fe
- right_knee
- right_ankle
  points: 
    - 
      positions: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
      velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
      accelerations: []
      effort: []
      time_from_start: 
        secs: 0
        nsecs: 200000000
    - 
      positions: [-0.0323, 0.3551, 0.3478, 0.0886, 0.0004, 0.0104, -0.0036, 0.0]
      velocities: [-0.0729, 0.0, 0.255, 0.0209, 0.0009, 0.0213, -0.0073, 0.0]
      accelerations: []
      effort: []
      time_from_start: 
        secs: 0
        nsecs: 983000000
    - 
      positions: [-0.0338, 0.3551, 0.3522, 0.0888, 0.0004, 0.0108, -0.0038, 0.0]
      velocities: [-0.0741, -0.0, 0.211, 0.0, 0.0009, 0.0214, -0.0074, 0.0]
      accelerations: []
      effort: []
      time_from_start: 
        secs: 1
        nsecs:   2399999
    - 
      positions: [-0.0391, 0.3551, 0.3603, 0.0888, 0.0005, 0.0123, -0.0043, 0.0]
      velocities: [-0.0777, -0.0, 0.0, -0.0004, 0.0009, 0.0217, -0.0074, 0.0]
      accelerations: []
      effort: []
      time_from_start: 
        secs: 1
        nsecs:  79700000
    - 
      positions: [-0.116, 0.3551, 0.3672, 0.0866, 0.0014, 0.0265, -0.0087, 0.0]
      velocities: [-0.0844, -0.0001, 0.0124, -0.0035, 0.001, 0.0038, 0.0, 0.0]
      accelerations: []
      effort: []
      time_from_start: 
        secs: 1
        nsecs: 953200000
    - 
      positions: [-0.1218, 0.355, 0.3681, 0.0864, 0.0015, 0.0266, -0.0005, 0.0]
      velocities: [-0.0818, -0.0001, 0.0126, -0.0035, 0.001, 0.0, 0.2148, 0.0]
      accelerations: []
      effort: []
      time_from_start: 
        secs: 2
        nsecs:  30800000
    - 
      positions: [-0.1674, 0.355, 0.3765, 0.0841, 0.0021, 0.7464, 0.7025, 0.0]
      velocities: [0.0, -0.0, 0.0011, -0.0002, 0.0001, 0.1072, 0.2964, 0.0]
      accelerations: []
      effort: []
      time_from_start: 
        secs: 2
        nsecs: 975000000
    - 
      positions: [-0.1674, 0.355, 0.3765, 0.0841, 0.0021, 0.7472, 0.7052, 0.0]
      velocities: [0.002, -0.0, 0.0009, -0.0001, 0.0001, 0.0, 0.2664, 0.0]
      accelerations: []
      effort: []
      time_from_start: 
        secs: 2
        nsecs: 992200000
    - 
      positions: [-0.1673, 0.355, 0.3765, 0.0841, 0.0021, 0.7472, 0.7076, 0.0]
      velocities: [0.0074, -0.0, 0.0006, 0.0, 0.0001, 0.0165, 0.2358, 0.0]
      accelerations: []
      effort: []
      time_from_start: 
        secs: 2
        nsecs: 994300000
    - 
      positions: [-0.1672, 0.355, 0.3765, 0.0841, 0.0021, 0.7471, 0.7096, 0.0]
      velocities: [0.0127, 0.0, 0.0, -0.0021, 0.0001, -0.0069, 0.2045, 0.0]
      accelerations: []
      effort: []
      time_from_start: 
        secs: 3
        nsecs:  13700000
    - 
      positions: [-0.1661, 0.3541, 0.3755, 0.0835, 0.0021, 0.7458, 0.7146, 0.0]
      velocities: [0.0335, -0.0517, -0.0559, -0.0201, 0.0, -0.0479, 0.073, 0.0]
      accelerations: []
      effort: []
      time_from_start: 
        secs: 3
        nsecs:  50399999
    - 
      positions: [-0.1658, 0.3533, 0.3747, 0.0833, 0.0021, 0.7452, 0.715, 0.0]
      velocities: [0.0386, -0.0716, -0.0774, -0.0244, 0.0002, -0.0579, 0.0, 0.0]
      accelerations: []
      effort: []
      time_from_start: 
        secs: 3
        nsecs:  59800000
    - 
      positions: [0.0209, 0.0119, 0.0057, 0.0013, 0.1041, 0.3931, 0.3693, 0.0]
      velocities: [0.277, 0.0, 0.0, -0.0135, 0.1628, -0.5323, -0.5625, 0.0]
      accelerations: []
      effort: []
      time_from_start: 
        secs: 4
        nsecs:         0
    - 
      positions: [0.0264, 0.0119, 0.0057, 0.0012, 0.1074, 0.3824, 0.358, 0.0]
      velocities: [0.2769, -0.0, -0.0, 0.0, 0.1629, -0.5324, -0.563, 0.0]
      accelerations: []
      effort: []
      time_from_start: 
        secs: 4
        nsecs:  19300000
    - 
      positions: [0.2085, 0.0102, 0.0049, 0.001, 0.2094, 0.0302, -0.0081, 0.0]
      velocities: [0.0339, -0.0032, -0.0015, -0.0003, 0.0, -0.0676, -0.0415, 0.0]
      accelerations: []
      effort: []
      time_from_start: 
        secs: 4
        nsecs: 959600000
    - 
      positions: [0.2092, 0.0101, 0.0048, 0.001, 0.2094, 0.0288, -0.0087, 0.0]
      velocities: [0.0184, -0.0033, -0.0016, -0.0003, -0.0029, -0.0377, 0.0, 0.0]
      accelerations: []
      effort: []
      time_from_start: 
        secs: 4
        nsecs: 987400000
    - 
      positions: [0.2094, 0.01, 0.0048, 0.001, 0.2093, 0.0284, -0.0087, 0.0]
      velocities: [0.0, -0.0033, -0.0016, -0.0003, -0.0056, -0.0171, 0.0001, 0.0]
      accelerations: []
      effort: []
      time_from_start: 
        secs: 5
        nsecs:  15699999
    - 
      positions: [0.2094, 0.01, 0.0048, 0.001, 0.2092, 0.0283, -0.0087, 0.0]
      velocities: [0.0024, -0.0034, -0.0016, -0.0003, -0.0069, 0.0, 0.0001, 0.0]
      accelerations: []
      effort: []
      time_from_start: 
        secs: 5
        nsecs:  17699999
    - 
      positions: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
      velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
      accelerations: []
      effort: []
      time_from_start: 
        secs: 8
        nsecs:         0
duration: 
  secs: 8
  nsecs:         0
sounds: []
```
